spring.application.name=gestor

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/kaysdb
spring.datasource.username=root
spring.datasource.password=P3rr0.Bris4.Nub3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql= true
#spring.jpa.hibernate.ddl-auto=update	